name: Deploy to Oracle Cloud Kubernetes

on:
   push:
      branches:
         - master

jobs:
   build-and-deploy:
      runs-on: ubuntu-latest

      steps:
         # Step 1: Checkout il codice
         - name: Checkout code
           uses: actions/checkout@v3

         # Step 2: Configura Node.js
         - name: Setup Node.js
           uses: actions/setup-node@v3
           with:
              node-version: "20" # Sostituisci con la tua versione

         # Step 3: Installa dipendenze e crea il build
         - name: Install dependencies
           run: npm install

         - name: Build application
           run: npm run build

         # Step 4: Estrai versione da package.json
         - name: Get version from package.json
           id: version
           run: echo "VERSION=$(node -p \"require('./package.json').version\")" >> $GITHUB_ENV

         # Step 5: Login al registro di Oracle
         - name: Log in to Oracle Container Registry
           run: echo "${{ secrets.OCR_PASSWORD }}" | docker login -u ${{ secrets.OCR_USERNAME }} ${{ secrets.OCR_REGISTRY }} --password-stdin

         # Step 6: Build e push dell'immagine Docker
         - name: Build and push Docker image
           run: |
              docker build -t ${{ secrets.OCR_REGISTRY }}/splash-api:${{ env.VERSION }} .
              docker push ${{ secrets.OCR_REGISTRY }}/splash-api:${{ env.VERSION }}

         # Step 7: Setup kubectl
         - name: Setup kubectl
           run: |
              echo "${{ secrets.KUBECONFIG }}" > kubeconfig
              export KUBECONFIG=$PWD/kubeconfig
              kubectl version

         # Step 8: Passa variabili dal file .env
         - name: Apply .env variables to ConfigMap
           run: |
              kubectl create configmap app-env --from-env-file=.env --dry-run=client -o yaml | kubectl apply -f -

         # Step 9: Deploy su Kubernetes
         - name: Deploy to Kubernetes
           run: |
              kubectl set image deployment/splash-api splash-api=${{ secrets.OCR_REGISTRY }}/splash-api:${{ env.VERSION }}
              kubectl rollout status deployment/splash-api
